#!/usr/bin/env python
import http.client, json, base64, time, sys, os, io, zbarlight, qrcode_terminal
from PIL import Image
from types import SimpleNamespace as Namespace

def setupSibs():
    conn = http.client.HTTPSConnection("site1.sibsapimarket.com:8444")

    with open('.apikey', 'r') as key_file:
        apikey = key_file.read()

    headers = {
        'x-ibm-client-id': apikey,
        'content-type': "application/json",
        'accept': "application/json"
        }
    
    return conn, headers

def genQR(conn, headers, amount):
    payload = "{\"amount\":{\"value\":" + amount + ",\"description\":\"qash usage\"}}"
    conn.request("POST", "/pixelscamp/apimarket/mbwaypurchases/qrcode-pixelscamp/v1/generate", payload, headers)

    res = conn.getresponse().read().decode('utf-8')
    # print(res)
    return json.loads(res, object_hook=lambda d: Namespace(**d))

def showQr(png):
    image = Image.open(io.BytesIO(png))

    codes = zbarlight.scan_codes(['qrcode'], image)
    qrcode_terminal.draw(str(codes[0], 'utf-8'))

def waitForMoneys(conn, headers, token):
    print("Waiting for your payment...")

    payload = "{\"qrCodeToken\":\"" + token + "\"}"

    while True:
        conn.request("POST", "/pixelscamp/apimarket/mbwaypurchases/qrcode-pixelscamp/v1/inquiry", payload, headers)

        res = conn.getresponse().read().decode('utf-8')
        data = json.loads(res, object_hook=lambda d: Namespace(**d))

        # print(res)

        if (data.statusCode == "000"):
            break
        if (data.statusCode == "101"):
            print("Payment timed out")
            exit(1)
        else:
            time.sleep(5)

    return data.qrCodePaymentToken

def finishPayment(conn, headers, token):
    payload = "{\"qrCodePaymentToken\":\"" + token + "\"}"

    conn.request("POST", "/pixelscamp/apimarket/mbwaypurchases/qrcode-pixelscamp/v1/purchase", payload, headers)

    res = conn.getresponse().read().decode('utf-8')
    data = json.loads(res, object_hook=lambda d: Namespace(**d))

    # print(res)

    if (data.statusCode == "APPR"):
        print("Done!")
    else:
        print("Payment failed")
        exit(1)

conn, headers = setupSibs()
sibsResp = genQR(conn, headers, sys.argv[1])
showQr(base64.decodestring(bytearray(sibsResp.qrCodeImage, 'utf-8')))
paymentToken = waitForMoneys(conn, headers, sibsResp.qrCodeToken)
finishPayment(conn, headers, paymentToken)
