#!/usr/bin/env python
import http.client
import json
import base64
import subprocess

from types import SimpleNamespace as Namespace

def genQR(payload):
    conn = http.client.HTTPSConnection("site1.sibsapimarket.com:8444")

    with open('.apikey', 'r') as key_file:
        apikey = key_file.read()

    headers = {
        'x-ibm-client-id': apikey,
        'content-type': "application/json",
        'accept': "application/json"
        }

    conn.request("POST", "/pixelscamp/apimarket/mbwaypurchases/qrcode-pixelscamp/v1/generate", payload, headers)

    res = conn.getresponse().read().decode('utf-8')
    # print(res)
    return json.loads(res, object_hook=lambda d: Namespace(**d))

def showQr(png):
    with open('tmp.png', 'wb') as image_file:
        image_file.write(png)
    subprocess.call(('xdg-open', 'tmp.png'))

sibsResp = genQR("{\"amount\":{\"value\":10,\"description\":\"qash usage\"}}")
png = base64.decodestring(bytearray(sibsResp.qrCodeImage, 'utf-8'))
showQr(png)
