#!/usr/bin/env python
import http.client
import json
import base64
import subprocess
import time

from types import SimpleNamespace as Namespace

def setupSibs():
    conn = http.client.HTTPSConnection("site1.sibsapimarket.com:8444")

    with open('.apikey', 'r') as key_file:
        apikey = key_file.read()

    headers = {
        'x-ibm-client-id': apikey,
        'content-type': "application/json",
        'accept': "application/json"
        }
    
    return conn, headers

def genQR(conn, headers, amount):
    payload = "{\"amount\":{\"value\":" + amount + ",\"description\":\"qash usage\"}}"
    conn.request("POST", "/pixelscamp/apimarket/mbwaypurchases/qrcode-pixelscamp/v1/generate", payload, headers)

    res = conn.getresponse().read().decode('utf-8')
    # print(res)
    return json.loads(res, object_hook=lambda d: Namespace(**d))

def showQr(png):
    with open('tmp.png', 'wb') as image_file:
        image_file.write(png)
    subprocess.call(('xdg-open', 'tmp.png'))

def waitForMoneys(conn, headers, token):
    print("Waiting for your payment...")

    payload = "{\"qrCodeToken\":\"" + token + "\"}"

    while True:
        conn.request("POST", "/pixelscamp/apimarket/mbwaypurchases/qrcode-pixelscamp/v1/inquiry", payload, headers)

        res = conn.getresponse().read().decode('utf-8')
        data = json.loads(res, object_hook=lambda d: Namespace(**d))

        if (data.statusCode == "000"):
            break
        if (data.statusCode == "101"):
            print("Payment timed out")
            exit(1)
        else:
            # print(res)
            time.sleep(5)

    return data.qrCodePaymentToken

def finishPayment(conn, headers, token):
    payload = "{\"qrCodePaymentToken\":\"" + token + "\"}"

    conn.request("POST", "/pixelscamp/apimarket/mbwaypurchases/qrcode-pixelscamp/v1/purchase", payload, headers)

    res = conn.getresponse().read().decode('utf-8')
    data = json.loads(res, object_hook=lambda d: Namespace(**d))

    if (data.statusCode == "APPR"):
        print("Done!")
    else:
        print("Payment failed")
        exit(1)

conn, headers = setupSibs()
sibsResp = genQR(conn, headers, "100")
showQr(base64.decodestring(bytearray(sibsResp.qrCodeImage, 'utf-8')))
paymentToken = waitForMoneys(conn, headers, sibsResp.qrCodeToken)
finishPayment(conn, headers, paymentToken)
